### PR TITLE
Adding data to database

### PR DESCRIPTION
**Pull request by anistad**
Added data to csv. Created an issue #4 with the new column categories for building_type, as non-residential buildings are added.

### CODE REVIEW

**Comment by nheeren** [comment]
Will merge this PR now. Could you also add the paper to `references/buildings.bib`, please?

**Comment by anistad** [comment]
Will do. I had forgotten, but reading my comment above I see that this data includes some non-residential buildings as well. Do you actually want non-residential buildings in this database? 😏

**Comment by nheeren** [comment]
There should already be some in there?!

**Comment by anistad** [comment]
Aha, all good then! 

I attached the references here (easier than opening a new pull req.): 
[ref.txt](https://github.com/nheeren/material_intensity_db/files/5026721/ref.txt)

**Pull request merged**
